# BEGIN_KITTY_THEME
# Nord
include current-theme.conf
# END_KITTY_THEME

font_family MesloLGS Nerd Font Mono 
bold_font auto
italic_font auto
bold_italic_font auto

font_size 16.0

hide_window_decorations yes

background_opacity 1
auto_reload_config yes

map cmd+r show_command_history

map cmd+alt+r reload_config
